### ISSUE TITLE
Unificação de Repositórios

### ISSUE THREAD

**Issue by gabrielferreiraa** [react-brasil/showcase-app-react-native#5]
Alô Comunidade,

Como todos sabem, temos este lindo repositório de [Empresas que usam React no Brasil](https://github.com/react-brasil/empresas-que-usam-react-no-brasil).

Nele, temos uma seção de **Projetos que usam React no Brasil**, que seria basicamente o que está sendo feito neste repositório. Porém para React e React Native.

Que tal unificarmos esses repositórios? 

Trazer os projetos que estão lá pra cá;
*ou*
Levar esses projetos daqui pra lá.

Caso a decisão seja trazer os projetos de lá pra cá, seria interessante renomear o repositório ára `showcase-app-react`, para termos qualquer projeto, sendo de Native ou não.

**Comment by nicholasess** [comment]
@gabrielferreiraa acredito ser duas coisas distintas.

No Empresas que usam..., a ideia é mostrar as empresas. Nesse repositório, a ideia são os aplicativos em si e não a tecnologia usada.

**Comment by nicholasess** [comment]
@gabrielferreiraa mas ainda não vejo necessidade de unificar. Senão teremos mais informações repetidas em outros repositórios.
Os projetos que usam React no Brasil nem deveria existir e deixar como está na lista principal.

**Comment by gabrielferreiraa** [comment]
Ok, acho que é isso mesmo! Como ninguém mais se manifestou vou fechar a issue.
