### ISSUE TITLE
O que seria links afiliado

### ISSUE THREAD

**Issue by enieber** [react-brasil/showcase-app-react-native#7]
nas regras existe esta regra, 

* Não colocar link afiliado

O que seria Links afiliado?

**Comment by gabrielferreiraa** [comment]
Fala @enieber, tudo certo?

[Nesse link você encontra uma descrição boa do que é link afiliado](https://www.techopedia.com/definition/1397/affiliate-link)

**Comment by gabrielferreiraa** [comment]
@enieber, estou fechando a issue. Qualquer dúvida pode abrir uma outra.
